# Use root/example as user/password credentials
version: '3.3'
 
services:
 
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    command: "--innodb_use_native_aio=0"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
    # <puerto publicado> : <Puerto de MySQL que corre dentro del contenedor>
        - '3306:3306'
    expose:
    # Se abre hacia fuera el puerto 3306 del contenedor
        - '3306'
    volumes:
        - /root/mysql:/var/lib/mysql
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080